site_name: Linux Tutorial
site_url: https://bibaijin.github.io/tutorial-linux
site_description: Linux 的学习心得
site_author: bibaijin

repo_url: https://github.com/bibaijin/tutorial-linux

theme: mkdocs
theme_dir: 'custom_theme'

pages:
- 首页: index.md
- Linux:
    - OS: linux/os.md
    - Shell: linux/shell.md
- 关于: about.md

markdown_extensions:
    - smarty
    - sane_lists
    - footnotes
    - tables

copyright: Copyright &copy; 2015 <a href="mailto:bibaijin@gmail.com">金比白</a>.
